import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Header from "@/components/layout/Header";
import Hero from "@/components/sections/Hero";
import Divider from "@/components/layout/Divider";
import Fullcard from "@/components/layout/Fullcard";
import ContactSection from "@/components/sections/ContactSection";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="">
        <main className={styles.main}>
          <div className={styles.fullcontainer}>

            <Header />
            <Hero />

            <Divider />

            <section className={styles.work}>

              <div className={styles.workHeaderContainer}>
                <div className={styles.workHeader}>Selected work ↓</div>
                <div className={styles.workSubHeader}>
                  Reach out for more detials
                </div>
              </div>

              <div className={styles.workWrapper}>
              <Fullcard />
              <Fullcard />
              <Fullcard />
              <Fullcard />
              </div>

            </section>

            <Divider />

            <ContactSection />
            
          </div>
        </main>
      </div>
    </>
  );
}
