import React, { useRef } from "react";
import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Header from "@/components/layout/Header";
import Hero from "@/components/sections/Hero";
import Divider from "@/components/layout/Divider";
import ContactSection from "@/components/sections/ContactSection";
import WorkSection from "@/components/sections/WorkSection";

export default function Home() {
  const workRef = useRef(null);
  const contactRef = useRef(null);

  const scrollTo = (ref) => {
    ref.current?.scrollIntoView({ behavior: "smooth" });
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <main className={styles.main}>
          <div className={styles.fullcontainer}>
            <Header onWorkClick={() => scrollTo(workRef)} onContactClick={() => scrollTo(contactRef)} />

            <Hero />

            <Divider />

            <div ref={workRef}>
              <WorkSection />
            </div>

            <Divider />

            <div ref={contactRef}>
              <ContactSection />
            </div>
          </div>
        </main>
      </div>
    </>
  );
}
