import React, { useRef } from "react";
import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Header from "@/components/layout/Header";
import Hero from "@/components/sections/Hero";
import Divider from "@/components/layout/Divider";
import ContactSection from "@/components/sections/ContactSection";
import WorkSection from "@/components/sections/WorkSection";

export default function Home() {
  const workRef = useRef(null);
  const contactRef = useRef(null);

  const scrollTo = (ref) => {
    ref.current?.scrollIntoView({ behavior: "smooth" });
  };

  return (
    <>
      <Head>
        <script async src="https://www.googletagmanager.com/gtag/js?id=G-8K33RXHHF7"></script>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              window.dataLayer = window.dataLayer || [];
              function gtag(){dataLayer.push(arguments);}
              gtag('js', new Date());
              gtag('config', 'G-8K33RXHHF7', {
                page_path: window.location.pathname,
              });
            `,
          }}
        />
        
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Ajay Sai – Portfolio</title>
        <link rel="icon" href="/favicon.svg" />
        
        
      </Head>

      <div>
        <main className={styles.main}>
          <div className={styles.fullcontainer}>
            <Header
              onWorkClick={() => scrollTo(workRef)}
              onContactClick={() => scrollTo(contactRef)}
            />

            <Hero />

            <Divider />

            <div ref={workRef}>
              <WorkSection link={"https://medium.com/@ajaysaiux/why-86-of-users-struggled-with-voice-setup-and-how-were-solving-it-f4c44f542bf9"} />
            </div>

            <Divider />

            <div ref={contactRef}>
              <ContactSection />
            </div>

          </div>
        </main>
      </div>
    </>
  );
}
